name: Issue Team sync

on:
  issues:
    types:
      - opened
      - edited

concurrency:
  group: issue-team-sync-${{ github.repository }}-${{ github.event.issue.number }}
  cancel-in-progress: true

jobs:
  sync-team:
    name: Synchronize Team issue field

    uses: ourosafra/.github/.github/workflows/sync-issue-team.yml@main

    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}

    secrets:
      projects_app_private_key: ${{ secrets.PROJECTS_APP_PRIVATE_KEY }}
